db_username       = "auroraserverless"      # Input Database username
db_password       = "<input_db_password>" # Input Database password
route53_zone_id   = "<input_route53_zone_id>" # Input your public hosted zone Route53 ID
route53_zone_name = "<input_route53_zone_name>" # Input your Route53 Zone Name
keycloak_username = "demo_user"
keycloak_password = "<input_keycloak_password" # Input a password for accsessing Keycloak Server
cert_arn          = "<input_your_acm_cert_arn" # Input your ACM Cert ARN
database_name     = "keycloakdemo"
environment       = "dev"
cluster_version   = "1.27"